GET http://localhost:3003/api/blogs
 


### 
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhbWl0YSIsImlkIjoiNjM3ZGUxOGM2ZGNjMjQyOWJmNmJjZmFjIiwiaWF0IjoxNjY5MTk0MTQyfQ.G32xlDlbJxg3W_u7PaUc1o9Bp1TsqKQFdteI51i6LeI

{

"title": "thelegend new created with token",
"author": "Hiraws",
"url":"dbcjdbj",
"likes":2,
"userId":"637dcd477c1247471cba86a1"
}


###

POST http://localhost:3003/api/users
content-type: application/json

{

"username": "Ramita",
"name": "Hirawsnmnmnn",
"password":"Ramita"
}


###
POST http://localhost:3003/api/login/
content-type: application/json

{

"username":"Ramita",
"password":"Ramita"
}