GET http://localhost:3003/api/blogs
 


### 
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbnUiLCJpZCI6IjYzOTAyNzVhNjQ1MTNkMmM5MmJhNDkzZCIsImlhdCI6MTY3MDM5MTc1OH0.B7UQQA-Mydy2EJH-Y6mGWr4X2FJ0J6ADvDy1RSynz7o

{
"title": " just a trial by user anu",
"author": "anu",
"url":"jpt",
"likes":5
}



###

POST http://localhost:3003/api/users
content-type: application/json

{

"username": "anu",
"name": "kanu",
"password":"anu"
}


###
POST http://localhost:3003/api/login/
content-type: application/json

{

"username":"sanu",
"password":"sanu"
}


###

DELETE http://localhost:3003/api/blogs/6390734cd11763e0e637984f
content-type: application/json
Authorization:  bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbnUiLCJpZCI6IjYzOTAyNzVhNjQ1MTNkMmM5MmJhNDkzZCIsImlhdCI6MTY3MDM5MTc1OH0.B7UQQA-Mydy2EJH-Y6mGWr4X2FJ0J6ADvDy1RSynz7o



