GET http://localhost:3003/api/blogs
 


### 
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1ZGVzaCIsImlkIjoiNjM4MDRiZjZjOTJlMDRjZjk0NzljYTQzIiwiaWF0IjoxNjY5MzUyNDY4fQ.NmmzUyEMpgXTZZbPvwx-PubYf_kcCAj2FMt4OyXy2Ts

{

"title": "thelegend new oneanxdan created with n",
"author": "sudesh",
"url":"dbcjdbj",
"likes":2
}


###

POST http://localhost:3003/api/users
content-type: application/json

{

"username": "Manjita",
"name": "Rajan",
"password":"Manjita"
}


###
POST http://localhost:3003/api/login/
content-type: application/json

{

"username":"sudesh",
"password":"sudesh"
}


###
DELETE http://localhost:3003/api/blogs/6380514abb5a1fe825aea52a
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1ZGVzaCIsImlkIjoiNjM4MDRiZjZjOTJlMDRjZjk0NzljYTQzIiwiaWF0IjoxNjY5MzUyNDY4fQ.NmmzUyEMpgXTZZbPvwx-PubYf_kcCAj2FMt4OyXy2Ts
